### PR TITLE
Improved device donfigurability, enhanced profiling, several performance and usability enhancements

### PR DESCRIPTION
**Pull request by barneypitt**
See 

https://groups.google.com/forum/#!topic/aparapi-discuss/5KbUuidB2Ck 
https://groups.google.com/forum/#!topic/aparapi-discuss/wnVcLllyU-U
https://groups.google.com/forum/#!topic/aparapi-discuss/Hh-8QCmxF14

for details

### CODE REVIEW

**Comment by Ryan-LaMothe-PNNL** [comment]
Thank you for your contribution!

**Comment by iotamudelta** [comment]
Is it possible that there is no definition of KernelPreferences in the patch?

I get a lot of:
aparapi/com.amd.aparapi/src/java/com/amd/aparapi/internal/kernel/KernelManager.java:127: error: cannot find symbol
    [javac]          KernelPreferences kernelPreferences = preferences.get(kernel.getClass());
    [javac]          ^
    [javac]   symbol:   class KernelPreferences
    [javac]   location: class KernelManager

errors in the build.

**Comment by barneypitt** [comment]
I'll take a look right away.

**Comment by barneypitt** [comment]
Yep, my bad.

I'll prepare a patch shortly, in the mean time if you want to compile it 
the source pasted below.

Cheers



package com.amd.aparapi.internal.kernel;

import com.amd.aparapi.*;
import com.amd.aparapi.device.*;

import java.util.*;

public class KernelPreferences
{
    private final Class<?extends Kernel>kernelClass;
    private final KernelManagermanager;
    private volatile LinkedList<Device>preferredDevices =null;
    private final LinkedHashSet<Device>failedDevices =new LinkedHashSet<>();

    public KernelPreferences(KernelManager manager, Class<?extends Kernel> kernelClass) {
       this.kernelClass = kernelClass;
       this.manager = manager;
    }

    /** What Kernel subclass is this the preferences for? */ public Class<?extends Kernel> getKernelClass() {
       return kernelClass;
    }

    public List<Device> getPreferredDevices(Kernel kernel) {
       maybeSetUpDefaultPreferredDevices();

       if (kernel ==null) {
          return Collections.unmodifiableList(preferredDevices);
       }
       List<Device> localPreferredDevices =new ArrayList<>();
       ArrayList<Device> copy;
       synchronized (preferredDevices) {
          copy =new ArrayList(preferredDevices);
       }
       for (Device device : copy) {
          if (kernel.isAllowDevice(device)) {
             localPreferredDevices.add(device);
          }
       }
       return Collections.unmodifiableList(localPreferredDevices);
    }

    synchronized void setPreferredDevices(LinkedHashSet<Device> _preferredDevices) {
       if (preferredDevices !=null) {
          preferredDevices.clear();
          preferredDevices.addAll(_preferredDevices);
       }
       else {
          preferredDevices =new LinkedList<>(_preferredDevices);
       }
       failedDevices.clear();
    }

    public Device getPreferredDevice(Kernel kernel) {
       List<Device> localPreferredDevices = getPreferredDevices(kernel);
       return localPreferredDevices.isEmpty() ?null : localPreferredDevices.get(0);
    }

    synchronized void markPreferredDeviceFailed() {
       if (preferredDevices.size() >0) {
          failedDevices.add(preferredDevices.remove(0));
       }
    }

    private void maybeSetUpDefaultPreferredDevices() {
       if (preferredDevices ==null) {
          synchronized (this) {
             if (preferredDevices ==null) {
                preferredDevices =new LinkedList<>(manager.getDefaultPreferences().getPreferredDevices(null));
             }
          }
       }
    }

    public List<Device> getFailedDevices() {
       return new ArrayList<>(failedDevices);
    }
}

**Comment by Ryan-LaMothe-PNNL** [comment]
All merged, please re-test

**Comment by iotamudelta** [comment]
There is still an issue with a missing import, creating pull request for this now.

**Comment by Ryan-LaMothe-PNNL** [comment]
Please continue to test. Thanks!

**Pull request merged**
